-- MySQL Script generated by MySQL Workbench
-- Tue 12 Nov 2019 04:59:06 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema predictor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `predictor` ;

-- -----------------------------------------------------
-- Schema predictor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `predictor` DEFAULT CHARACTER SET utf8 ;
USE `predictor` ;

-- -----------------------------------------------------
-- Table `predictor`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movies` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `rating` ENUM('TP', '-12', '-16', '-18') NULL,
  `production_budget` INT NULL,
  `marketing_budget` INT NULL,
  `duration` INT NULL,
  `release_date` DATE NULL,
  `is3d` TINYINT NULL,
  `synopsis` TEXT NULL,
  `original_title` VARCHAR(255) NOT NULL,
  `imdb_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `imdb_id_UNIQUE` (`imdb_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`people` ;

CREATE TABLE IF NOT EXISTS `predictor`.`people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`role` ;

CREATE TABLE IF NOT EXISTS `predictor`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`movie_people_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movie_people_roles` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movie_people_roles` (
  `movie_id` INT NOT NULL,
  `people_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `people_id_idx` (`people_id` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `movie_mpr_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `predictor`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `people_mpr_id`
    FOREIGN KEY (`people_id`)
    REFERENCES `predictor`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `position_mpr_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `predictor`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`movie_origin_country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movie_origin_country` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movie_origin_country` (
  `movie_id` INT NOT NULL,
  `country_iso2` CHAR(2) NOT NULL,
  INDEX `movie_id_idx` (`movie_id` ASC) INVISIBLE,
  INDEX `country_iso2_idx` (`country_iso2` ASC) VISIBLE,
  CONSTRAINT `movie_oc_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `predictor`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`companies` ;

CREATE TABLE IF NOT EXISTS `predictor`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `predictor`.`movie_companies_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `predictor`.`movie_companies_role` ;

CREATE TABLE IF NOT EXISTS `predictor`.`movie_companies_role` (
  `movie_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `company_id_idx` (`company_id` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `movie_mcr_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `predictor`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_mcr_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `predictor`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_mcr_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `predictor`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
